### ISSUE TITLE
More thorough testing of TSC.

### ISSUE THREAD

**Issue by rainwoodman** [rainwoodman/pmesh#10]
https://github.com/rainwoodman/nbodykit/pull/1

TSC doesn't seem to be correct.

**Comment by nickhand** [comment]
It looks like we have sort of reflection of the previous results. 

with `BoxSize = [1., 1., 1.]` and `Nmesh = [2, 2, 2]`, and ``pos = [[0.5, 0.5, 0.5]]``, comparing old and new gives:

old: 
``` python
>> real[0]
array([[ 0.421875,  0.140625],
       [ 0.140625,  0.046875]])
>> real[1]
array([[ 0.140625,  0.046875],
       [ 0.046875,  0.015625]])
```

new: 
``` python
>> real[0]
RealField([[ 0.015625,  0.046875],
       [ 0.046875,  0.140625]])
>> real[1]
RealField([[ 0.046875,  0.140625],
       [ 0.140625,  0.421875]])
```

**Comment by rainwoodman** [comment]
Is it a periodicity problem?

**Comment by rainwoodman** [comment]
The peak should be at [1, 1, 1] in mesh units, so it appears the old code was broken.

**Comment by nickhand** [comment]
I think this is an nbodykit issue --> setting CIC and TSC in the config file give the same results, so paintbrush is getting lost somewhere I think

**Comment by nickhand** [comment]
okay, I think I broke your logic in painter; let me see if I can fix this

**Comment by rainwoodman** [comment]
I played with the new TSC and deconvolved it, doesn't look too bad...
![index](https://cloud.githubusercontent.com/assets/138060/17639639/e3fbbb3c-60a8-11e6-8d93-b17dc60a1547.png)

**Comment by nickhand** [comment]
When actually using TSC, and generating a random field, the AnisotropicTSC correction still does not fully correct the power spectrum back to shot noise (it should be exact) 

The code for AnisotropicTSC looks okay to me, so I'm not sure what is going on. It's still possible this could be on the nbodykit side of things.

![figure_1](https://cloud.githubusercontent.com/assets/2262496/17639693/86bbd866-60a9-11e6-92ce-ec0641584f81.png)

**Comment by nickhand** [comment]
does the TSC derivative have a bug? I'm not sure the units of x, but shouldn't it have a `factor**2`

**Comment by rainwoodman** [comment]
Here is my  deconvlve kernel:

 KN = 2 * pi / c.BoxSize * c.Nmesh  *0.5
 decov = prod([
        1 - sin(pi / 2 * k / kn) ** 2 + 2 / 15. * sin(pi / 2 * k/ kn) ** 4
        for k, kn in zip(c.x, KN)
    ])

The TSC derivative is not tested at all. I don't think it shall have factor ** 2 though. Factor is because of the abs(x * hinv) call. The derivative is d (kernel_func) / dx.

**Comment by rainwoodman** [comment]
But indeed I don't get it flat neither in my test.

**Comment by nickhand** [comment]
What is going on [here](https://github.com/rainwoodman/pmesh/blob/master/pmesh/_window_imp.cxx#L180-L183)?

I imagine that if/else should actually be different?

**Comment by rainwoodman** [comment]
I initially thought it were the same. Then thought it may be different. but eventually figured it is the same.

**Comment by rainwoodman** [comment]
I suspect for TSC the deconvolution can't be exact. Because the window spreads over three points ? Do you still have the original paper where this window is derived?

**Comment by nickhand** [comment]
I believe it should be exact. The expression from Jing et al that we are using is derived in [Donghui Jeong's thesis](http://www.personal.psu.edu/duj13/dissertation/djeong_diss.pdf)

Eq. 7.52 gives the deconvolution we are using and then Eq. 7.21 is the window you have implemented, I think?

**Comment by rainwoodman** [comment]
I found Jing's 2005 paper and it was exact. So we didn't implement TSC window correctly. Was your old window exact?

**Comment by nickhand** [comment]
Yes, this test works for the implementation in tsc.py. I think we just need to compare the C window to [these lines](https://github.com/rainwoodman/pmesh/blob/master/pmesh/tsc.py#L80-L89]

**Comment by rainwoodman** [comment]
rint rounds to the nearest integer.

**Comment by nickhand** [comment]
ah yes, you are doing floor? I had thought to get the NGP index, you need to do rint, no?

**Comment by rainwoodman** [comment]
I think of this as a function with support of 3. So if I call the round down 0, then I shall start from -1 (left). -1, 0, 1 are nonzero.

**Comment by rainwoodman** [comment]
I see the problem now. I can't assert 2 is zero.

**Comment by nickhand** [comment]
with rainwoodman/nbodykit#2, this fixes the issue for me

**Comment by nickhand** [comment]
and it fixes the nbodykit pandas HDF test result

**Comment by rainwoodman** [comment]
The order 3 lanczos still looks strange. But I'll tag a 0.0.14 so we can use tsc.

![index](https://cloud.githubusercontent.com/assets/138060/17640392/75dfd5b0-60b3-11e6-9d90-278a4a96cd91.png)
