### ISSUE TITLE
white noise phases of complex field not uniform

### ISSUE THREAD

**Issue by nickhand** [rainwoodman/pmesh#15]
looks something is wrong here...

![figure_1](https://cloud.githubusercontent.com/assets/2262496/21245295/91dc47b4-c2d6-11e6-9ea9-a69a258afd52.png)

**Comment by nickhand** [comment]
Looks like there are too many phases with exactly 0, -pi, pi as there values. I didn't see anything obvious in the code, @rainwoodman will you take a look?

**Comment by nickhand** [comment]
I think this is a bug when determining when to just use the hermitian conjugate. If Nz is even, only 8 modes should be hermitian conjugates, given by the (i,j,k) permutations using indices 0 and Nz. Currently I think the entire k=Nz plane is hermitian symmetric...

**Comment by rainwoodman** [comment]
We currently set every mode at nyquist to zero.. It is a bit ambiguous with
Gadget since in Gadget the transfer function is immediately applied. I'll
take a look.

**Comment by nickhand** [comment]
Currently with this scheme, there's a bit more scatter in the linear grid
power spectrum than you would expect with Gaussian statistics

**Comment by rainwoodman** [comment]
![figure_1-2](https://cloud.githubusercontent.com/assets/138060/21247660/1ada234c-c2e6-11e6-92a7-7d95dae135e1.png)

I allowed the nyquist to float. How does this look?

**Comment by nickhand** [comment]
fixed by #16
