### ISSUE TITLE
Add c2c

### ISSUE THREAD

**Issue by eelregit** [rainwoodman/pmesh#30]
would be possible? For example it would make things like the ConvolvedPower in nbodykit easier.

**Comment by rainwoodman** [comment]
Is it because you want to pack two real fields into a single complex field?

**Comment by eelregit** [comment]
FFT of spherical harmonics weighted density field as an example. Just more
convenient to do with a c2c method.

**Comment by eelregit** [comment]
Hmmm... really_complex? ;)

**Comment by rainwoodman** [comment]
I think the problem is that ComplexField shall be renamed to
HermitianField.

**Comment by eelregit** [comment]
Good point.

**Comment by rainwoodman** [comment]
The branch is merged.
