### ISSUE TITLE
pmesh MPI bug

### ISSUE THREAD

**Issue by samiransen23** [rainwoodman/pmesh#44]
I've narrowed down the problems in issue #43 or #42 to something that is directly connected to the MPI communication of pmesh, when a `pmesh.pm.ParticleMesh(` object is created repeatedly.  There is no molecular dynamics, no pmesh fields, nothing, so it's a minimalist approach to investigate the problem.

Here is an algorithm which does the following in a loop running `n_steps` times:
Step 1. Create `ParticleMesh object` with `BoxSize = box_size`
Step 2. Change `box_size`
Step 3. Go back to Step 1

Here is the minimalist code (call it `pmesh_debug.py`) that does it:
```python
import numpy as np
import h5py
from mpi4py import MPI
import os
import pmesh.pm as pmesh
import sys
import warnings
from pprint import pprint

def initialize_pm(box_size):
    with warnings.catch_warnings():
        warnings.filterwarnings(action="ignore",category=np.VisibleDeprecationWarning)
        pm = pmesh.ParticleMesh(
            [24,24,24], BoxSize=box_size, dtype="f4", comm=MPI.COMM_WORLD
        )
    phi = None
    return (pm, phi)

if __name__ == "__main__":
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    size = comm.Get_size()
    dtype = np.float32
    box_size = [4,4,4]
    alpha = 0.99
    n_steps = 5000
    (pm, phi) = initialize_pm(box_size)
    for step in range(n_steps):
        box_size = [alpha * box_size[i] for i in range(3)]
        (pm, phi) = initialize_pm(box_size)

        if rank==0 and step != 0:
            print('step:', step,'\n',
                      'pm:',pm,'\n',
                      #'pm attrs:',vars(pm).keys(),'\n'
                      'pm box attr:',pm.BoxSize,'\n',
                      )

```
Run: `mpirun -n 4 python3  pmesh_debug.py`
Running a debugger shows memory-buildup throughout the run.

Run: `mpirun -n 1 python3  pmesh_debug.py`
No memory buildup and runs much faster.

So it boils down to the "MPI communication" of pmesh. To me it seems there is either a bug in the communication even when done just once, but is unnoticeable OR there is residual garbage that stays in memory when `n>1` (ONLY) . I'd really appreciate your help on this.

**Comment by rainwoodman** [comment]
Thanks for the report. I haven't run you script yet, but this line could be of interest?
https://github.com/rainwoodman/pmesh/blob/master/pmesh/pm.py#L1373

We use a pm_cache to speed up creation of PM objects. Because your script is using different box sizes, the _pm_cache does receive more instances of structures.

I think most attributes derived from box-sizes are quick to create -- so one way to curb the memory use for your use case is to
remove box_size from the cache key and adjust the initialization logic accordingly.

**Comment by samiransen23** [comment]
Thanks for the reply and the lead into where to look :) @rainwoodman

**Comment by samiransen23** [comment]
I removed box information from `cache.args()` in `pm.py` so that a different box size does not trigger the make_duo function. To me it seems the the `partition`, `fplan` and `bplan` do not carry box information and we can keep using the initially made ones even though the box size may have changed. @rainwoodman 
https://github.com/rainwoodman/pmesh/blob/5c3a2263f297891923a16674029a2b01e2188f8c/pmesh/pm.py#L1373-L1375

**Comment by rainwoodman** [comment]
Thanks. I committed the change. It is indeed obvious. :)
